[features]
seeds = false
[programs.devnet]
nft_bazzar = "DgEPk8UKFtZJkccQagn2NUkmKQXUDZERPiMijmFaMrdQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/anton.lempii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
