[features]
seeds = false
[programs.testnet]
nft_bazzar = "7GCSd3CwKCkdwRds5eHNDe6zasKSk8P4i5Svo61obhix"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "/Users/anton.lempii/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
